// ─── BREAKFASTS ───────────────────────────────────────────────
export const BREAKFASTS = [
  {
    id: 'b0', emoji: '🫐', type: 'Breakfast',
    name: 'Overnight Oats with Blueberries & Walnuts',
    time: '10 min + overnight', servings: 2, cost: '$2.40',
    calories: 420, protein: '12g', fiber: '11g', difficulty: 'Easy',
    color: '#EAF4EE',
    tags: ['omega-3', 'antioxidants', 'heart', 'fiber'],
    ingredients: [
      '1 cup rolled oats',
      '1½ cups unsweetened almond milk',
      '2 tbsp chia seeds',
      '1 tbsp pure maple syrup',
      '1 cup fresh blueberries',
      '¼ cup chopped walnuts',
      '½ tsp vanilla extract',
      'Pinch of cinnamon',
    ],
    steps: [
      'Combine oats, almond milk, chia seeds, maple syrup, vanilla, and cinnamon in a mason jar or large bowl.',
      'Stir well to combine. Cover tightly and refrigerate overnight (minimum 6 hours).',
      'In the morning, stir the oat mixture. Add a splash of almond milk if too thick.',
      'Top with fresh blueberries and chopped walnuts. Serve immediately.',
    ],
    science: 'Blueberries contain anthocyanins shown to improve memory by 20–25% in older adults (Devore et al., JAMA Internal Medicine, 2012). Beta-glucan in oats reduces LDL cholesterol by 5–10% at 3g/day (EFSA, 2011). Walnuts are the richest nut source of ALA omega-3 — each serving provides ~2.5g.',
    benefits: [
      'Memory improvement via blueberry anthocyanins (20–25%)',
      'LDL reduced 5–10% by oat beta-glucan',
      '2.5g ALA omega-3 from walnuts per serving',
      '11g fiber per serving for microbiome diversity',
    ],
    shopping: 'Oats: Quaker or Bob\'s Red Mill (Walmart ~$3/tub) | Blueberries: Costco Kirkland frozen wild ($10/3lb) | Walnuts: Fisher brand ($5) | Almond milk: Silk or Almond Breeze ($3–4, all stores)',
  },
  {
    id: 'b1', emoji: '🌟', type: 'Breakfast',
    name: 'Turmeric Golden Milk Oatmeal',
    time: '15 min', servings: 2, cost: '$1.80',
    calories: 380, protein: '11g', fiber: '8g', difficulty: 'Easy',
    color: '#FFF8E7',
    tags: ['anti-inflammatory', 'brain', 'curcumin'],
    ingredients: [
      '1 cup steel-cut oats',
      '2 cups oat milk',
      '1 tsp turmeric powder',
      '½ tsp cinnamon',
      '¼ tsp ginger powder',
      'Pinch of black pepper',
      '1 tbsp honey or maple syrup',
      '1 banana (sliced)',
      '2 tbsp pumpkin seeds',
    ],
    steps: [
      'Bring oat milk to a gentle simmer over medium heat.',
      'Add oats and stir. Cook 20–25 minutes, stirring occasionally.',
      'Add turmeric, cinnamon, ginger, and black pepper in the last 5 minutes.',
      'Stir in honey or maple syrup. Top with banana slices and pumpkin seeds.',
    ],
    science: 'Curcumin in turmeric inhibits NF-κB — the master inflammatory transcription factor. Black pepper piperine increases curcumin bioavailability by 2000% (Shoba et al., Planta Medica, 1998). Steel-cut oats have a glycemic index of 55 vs 83 for instant oats, providing 30% more stable blood glucose.',
    benefits: [
      'Curcumin inhibits NF-κB — master inflammation gene',
      'Black pepper boosts curcumin bioavailability 2000%',
      'Steel-cut oats: GI=55 (vs instant 83) — 30% more stable glucose',
      'Pumpkin seeds provide zinc, magnesium, and plant omega-3',
    ],
    shopping: 'Turmeric: Indian grocery (70% cheaper than McCormick, ~$4) | Oat milk: Oatly Target ($5) | Pumpkin seeds: Trader Joe\'s ($4) | Steel-cut oats: Bob\'s Red Mill ($4)',
  },
  {
    id: 'b2', emoji: '🥑', type: 'Breakfast',
    name: 'Avocado Toast with Hemp Seeds & Poached Egg',
    time: '15 min', servings: 2, cost: '$3.20',
    calories: 520, protein: '22g', fiber: '12g', difficulty: 'Medium',
    color: '#EAF4EE',
    tags: ['choline', 'brain', 'complete protein'],
    ingredients: [
      '4 slices whole grain sourdough',
      '2 ripe Hass avocados',
      '4 large eggs',
      '2 tbsp hemp seeds',
      '1 lemon (juice)',
      'Red pepper flakes',
      'Sea salt & black pepper',
      '1 tsp white vinegar (for poaching)',
    ],
    steps: [
      'Toast sourdough until golden and crispy. Mash avocados with lemon juice, salt, and pepper.',
      'Bring a medium saucepan of water to a gentle simmer (not boiling). Add white vinegar.',
      'Create a gentle whirlpool with a spoon. Crack each egg into the center. Cook 3 minutes for runny yolk.',
      'Spread avocado generously on toast. Top with poached egg. Sprinkle hemp seeds and red pepper flakes.',
    ],
    science: 'Each egg provides 125mg choline — the precursor to acetylcholine, the primary memory neurotransmitter. Adequate dietary choline is associated with 25% better cognitive performance (Nurk et al., AJCN, 2010). Hemp seeds contain all essential amino acids at a 3:1 omega-6:omega-3 ratio.',
    benefits: [
      '125mg choline per egg for acetylcholine synthesis',
      '25% better cognition with adequate choline (clinical evidence)',
      'Hemp seeds: all essential amino acids + ideal omega ratio',
      'Sourdough fermentation doubles mineral bioavailability',
    ],
    shopping: 'Avocados: Costco 6-pack (~$6) | Sourdough: Dave\'s Killer Bread ($5–6) | Hemp seeds: Manitoba Harvest Whole Foods ($8) | Eggs: Vital Farms pasture-raised ($7/dozen)',
  },
  {
    id: 'b3', emoji: '🍇', type: 'Breakfast',
    name: 'Acai Bowl with Granola & Cacao Nibs',
    time: '10 min', servings: 2, cost: '$4.50',
    calories: 460, protein: '10g', fiber: '9g', difficulty: 'Easy',
    color: '#F0ECFF',
    tags: ['antioxidants', 'brain', 'fiber'],
    ingredients: [
      '2 packs (200g) frozen acai puree',
      '1 ripe banana',
      '½ cup frozen mixed berries',
      '¼ cup unsweetened almond milk',
      '½ cup low-sugar granola',
      '2 tbsp toasted coconut flakes',
      '1 tbsp raw honey',
      'Fresh kiwi slices',
      '1 tbsp cacao nibs',
    ],
    steps: [
      'Place frozen acai, banana, berries, and almond milk in a high-speed blender.',
      'Blend until very thick and smooth — the consistency should be like soft-serve, not liquid.',
      'Pour into two bowls immediately.',
      'Top with granola, coconut, kiwi slices, cacao nibs, and a drizzle of honey. Serve cold.',
    ],
    science: 'Acai berries have an ORAC score of ~15,000 per 100g — one of the highest of any food tested. Cacao flavanoids increase nitric oxide production, improving cerebral blood flow. A 2020 Nutrients study found regular cacao consumption improved processing speed and working memory.',
    benefits: [
      'Acai: highest ORAC antioxidant score of any food (~15,000/100g)',
      'Cacao flavanoids improve cerebral blood flow via nitric oxide',
      'Kiwi: 102% DV vitamin C per fruit',
      'Complex carbohydrates for sustained energy release',
    ],
    shopping: 'Acai: Sambazon brand Whole Foods/Publix (~$6/pack) | Granola: KIND Healthy Grains Target ($5) | Cacao nibs: Navitas Organics Amazon ($7) | Coconut flakes: Bob\'s Red Mill ($4)',
  },
  {
    id: 'b4', emoji: '🍓', type: 'Breakfast',
    name: 'Greek Yogurt Parfait with Walnuts & Berries',
    time: '5 min', servings: 2, cost: '$2.80',
    calories: 390, protein: '24g', fiber: '7g', difficulty: 'Easy',
    color: '#FDE8E8',
    tags: ['probiotics', 'protein', 'brain'],
    ingredients: [
      '2 cups full-fat Greek yogurt',
      '1 cup strawberries (sliced)',
      '½ cup blueberries',
      '¼ cup walnuts',
      '3 tbsp granola',
      '1 tbsp ground flaxseed',
      '1 tsp honey per serving',
      '½ tsp vanilla extract',
    ],
    steps: [
      'Stir vanilla extract into Greek yogurt until well combined.',
      'Layer yogurt, fresh strawberries, and blueberries in two tall glasses or bowls.',
      'Add granola layer. Repeat yogurt and berry layers.',
      'Top with walnuts, ground flaxseed, and a drizzle of honey. Serve immediately.',
    ],
    science: 'Greek yogurt contains live Lactobacillus acidophilus and Bifidobacterium cultures. The gut produces approximately 95% of the body\'s serotonin. A 2019 meta-analysis in Frontiers in Psychiatry (n=34 studies) found probiotic supplementation significantly reduced depression and anxiety symptoms.',
    benefits: [
      '10+ billion live probiotic cultures per serving',
      'Gut microbiome produces 95% of body\'s serotonin',
      '24g complete protein — highest plant breakfast protein',
      'Flaxseed: 2.35g ALA omega-3 per tablespoon',
    ],
    shopping: 'Greek yogurt: Fage Total 5% or Chobani Full Fat (all stores $5–6) | Ground flaxseed: Bob\'s Red Mill Publix ($4) | Berries: Costco frozen ($10/3lb) | Walnuts: Fisher brand ($5)',
  },
  {
    id: 'b5', emoji: '🥭', type: 'Breakfast',
    name: 'Chia Seed Pudding with Mango & Coconut',
    time: '5 min + 4hr chill', servings: 2, cost: '$2.60',
    calories: 440, protein: '9g', fiber: '14g', difficulty: 'Easy',
    color: '#E8F5E9',
    tags: ['MCT', 'omega-3', 'fiber'],
    ingredients: [
      '6 tbsp black chia seeds',
      '2 cups full-fat coconut milk (canned)',
      '1 tbsp pure maple syrup',
      '1 tsp vanilla extract',
      '1 ripe mango (diced)',
      '2 tbsp toasted coconut flakes',
      '½ lime (zest and juice)',
    ],
    steps: [
      'Whisk chia seeds, coconut milk, maple syrup, and vanilla in a large bowl.',
      'Let mixture sit 15 minutes, then whisk again to break up any clumps.',
      'Cover and refrigerate at least 4 hours, or overnight, until thick and creamy.',
      'Toss diced mango with lime zest and juice. Serve pudding topped with mango and coconut flakes.',
    ],
    science: 'Chia seeds absorb 10× their weight in liquid, creating a gel matrix that slows gastric emptying and stabilizes blood glucose for 4–6 hours. Full-fat coconut milk provides MCTs that are converted to ketone bodies within 30 minutes — providing fast, alternative brain fuel (Page et al., Neurobiology of Aging, 2009).',
    benefits: [
      'MCTs converted to brain-fueling ketones within 30 minutes',
      'Chia gel stabilizes blood glucose for 4–6 hours',
      '14g fiber per serving feeds 500+ bacterial species',
      'Mango folate for dopamine and serotonin synthesis',
    ],
    shopping: 'Chia seeds: Nutiva Organic Costco ($12/2lb — best value) | Coconut milk: Thai Kitchen full-fat Publix ($2.50/can) | Mango: Costco frozen chunks ($10/4lb)',
  },
  {
    id: 'b6', emoji: '🫑', type: 'Breakfast',
    name: 'Tofu Scramble with Spinach & Bell Peppers',
    time: '20 min', servings: 2, cost: '$2.90',
    calories: 380, protein: '26g', fiber: '6g', difficulty: 'Medium',
    color: '#E0F5EE',
    tags: ['B12', 'lutein', 'complete protein'],
    ingredients: [
      '400g extra-firm tofu (pressed 10 min)',
      '2 tbsp extra virgin olive oil',
      '1 large red bell pepper (diced)',
      '2 cups fresh baby spinach',
      '¼ tsp ground turmeric',
      '2 tbsp nutritional yeast (B12-fortified)',
      '1 tsp garlic powder',
      '½ tsp cumin',
      'Salt & pepper to taste',
    ],
    steps: [
      'Press tofu for 10 minutes using paper towels and a heavy pan. Crumble into pea-sized pieces.',
      'Heat olive oil in a large non-stick skillet over medium-high heat. Sauté bell pepper 3 minutes.',
      'Add crumbled tofu, turmeric, garlic powder, cumin, salt, and pepper. Cook 5–6 minutes.',
      'Add spinach and nutritional yeast. Cook 2 more minutes until spinach wilts. Serve hot.',
    ],
    science: 'Nutritional yeast (B12-fortified) provides 2–4mcg B12 per 2 tbsp — critical for myelin sheath integrity. B12 deficiency causes irreversible neurological damage and is present in 40–90% of vegetarians without supplementation. Spinach lutein directly correlates with preserved cognitive function (Barnett et al., Nutritional Neuroscience, 2018).',
    benefits: [
      'B12 from fortified yeast prevents neurological damage',
      'Spinach lutein preserves frontal cortex cognitive function',
      '26g complete plant protein — exceeds typical egg breakfast',
      'Turmeric curcumin + olive oil polyphenols synergize',
    ],
    shopping: 'Tofu: Nasoya Extra Firm Publix ($3) | Nutritional yeast: Bragg\'s Premium Whole Foods ($7 — always choose B12-fortified) | Spinach: Costco pre-washed ($5/1.5lb)',
  },
];

// ─── LUNCHES ──────────────────────────────────────────────────
export const LUNCHES = [
  {
    id: 'l0', emoji: '🫙', type: 'Lunch',
    name: 'Mediterranean Quinoa Power Bowl',
    time: '25 min', servings: 2, cost: '$4.20',
    calories: 580, protein: '28g', fiber: '14g', difficulty: 'Medium',
    color: '#EAF4EE',
    tags: ['complete protein', 'Mediterranean', 'heart health'],
    ingredients: [
      '1 cup quinoa (well rinsed)',
      '2 cups water',
      '1 can chickpeas (drained, rinsed)',
      '1 English cucumber (diced)',
      '1 cup cherry tomatoes (halved)',
      '½ red onion (finely diced)',
      '½ cup Kalamata olives',
      '100g Greek feta cheese (crumbled)',
      '3 tbsp extra virgin olive oil',
      '1 lemon (juice)',
      '1 tsp dried oregano',
      'Fresh flat-leaf parsley',
    ],
    steps: [
      'Bring 2 cups water to boil. Add rinsed quinoa, reduce heat, cover and simmer 15 minutes.',
      'Fluff with fork. Let cool 10 minutes.',
      'Toss chickpeas with olive oil and paprika. Roast at 400°F for 20 minutes until crispy.',
      'Combine quinoa with cucumber, tomatoes, onion, olives. Dress with olive oil, lemon, oregano.',
      'Top with crumbled feta, crispy chickpeas, and fresh parsley.',
    ],
    science: 'The Mediterranean dietary pattern reduces cardiovascular disease risk by 33% and cognitive decline by 23% (Sofi et al., BMJ, 2008). Quinoa contains all 9 essential amino acids. Olive oil oleocanthal inhibits COX-1 and COX-2 with similar activity to ibuprofen.',
    benefits: [
      'Mediterranean diet: 33% lower cardiovascular disease risk',
      'Quinoa: one of few plants with all 9 essential amino acids',
      'Olive oil oleocanthal: natural COX inhibitor (ibuprofen mechanism)',
      'Chickpea prebiotics feed 500+ gut bacterial species',
    ],
    shopping: 'Quinoa: Ancient Harvest Costco ($12/5lb) | Chickpeas: Goya ($1/can) | Feta: Costco Greek block in brine ($8) | Kalamata olives: Trader Joe\'s ($4)',
  },
  {
    id: 'l1', emoji: '🍲', type: 'Lunch',
    name: 'Red Lentil Soup with Lemon & Cumin',
    time: '35 min', servings: 4, cost: '$1.80',
    calories: 320, protein: '20g', fiber: '16g', difficulty: 'Easy',
    color: '#FFF8E7',
    tags: ['folate', 'iron', 'lowers LDL'],
    ingredients: [
      '2 cups red lentils (rinsed)',
      '6 cups low-sodium vegetable broth',
      '1 large onion (diced)',
      '4 garlic cloves (minced)',
      '2 tsp ground cumin',
      '1 tsp ground turmeric',
      '½ tsp smoked paprika',
      '1 can (14oz) diced tomatoes',
      '2 tbsp extra virgin olive oil',
      '1 lemon (juice)',
      'Fresh cilantro or parsley',
      'Salt & black pepper',
    ],
    steps: [
      'Sauté diced onion in olive oil over medium heat for 5 minutes until softened.',
      'Add garlic, cumin, turmeric, and paprika. Cook 1 minute, stirring constantly.',
      'Add rinsed lentils, diced tomatoes, and broth. Bring to a boil.',
      'Reduce heat and simmer 20–25 minutes until lentils are completely soft.',
      'Blend half the soup with an immersion blender. Stir in lemon juice. Top with cilantro.',
    ],
    science: 'Red lentils reduce LDL cholesterol by an average of 0.14 mmol/L per serving (AJCN meta-analysis, 2014). One cup provides 90% DV folate — critical for homocysteine metabolism. Elevated homocysteine doubles Alzheimer\'s disease risk. Each 5 µmol/L reduction in homocysteine = 19% lower stroke risk.',
    benefits: [
      '90% daily folate per serving — prevents elevated homocysteine',
      'Lentils reduce LDL by 0.14 mmol/L (clinical meta-analysis)',
      '19% lower stroke risk per 5 µmol/L homocysteine reduction',
      '$1.80/serving — best nutrition-per-dollar meal possible',
    ],
    shopping: 'Red lentils: Goya ($2/lb all stores) or Indian grocery bulk ($1.20/lb) | Broth: Pacific Foods Low Sodium Costco ($12/12 cartons) | Budget tip: entire 4-serving pot costs $7.20',
  },
  {
    id: 'l2', emoji: '🥗', type: 'Lunch',
    name: 'Chickpea & Avocado Power Salad',
    time: '15 min', servings: 2, cost: '$3.80',
    calories: 490, protein: '16g', fiber: '13g', difficulty: 'Easy',
    color: '#E0F5EE',
    tags: ['lutein', 'nitrates', 'antioxidants'],
    ingredients: [
      '1 can chickpeas (drained, rinsed)',
      '2 ripe Hass avocados (cubed)',
      '2 cups baby arugula',
      '½ cup oil-packed sun-dried tomatoes (drained)',
      '¼ cup thinly sliced red onion',
      '2 tbsp capers (drained)',
      '3 tbsp extra virgin olive oil',
      '2 tbsp apple cider vinegar',
      '1 tsp Dijon mustard',
      '1 garlic clove (minced)',
      'Fresh basil',
      'Salt & black pepper',
    ],
    steps: [
      'Make dressing: whisk together olive oil, apple cider vinegar, Dijon mustard, garlic, salt, pepper.',
      'Toss chickpeas, arugula, sun-dried tomatoes, red onion, and capers with the dressing.',
      'Gently fold in cubed avocado to avoid mashing.',
      'Top with torn fresh basil leaves and extra cracked black pepper. Serve immediately.',
    ],
    science: 'Avocado lutein is selectively taken up by the brain\'s frontal cortex and inversely associated with cognitive decline. A 2017 Nutrients study found daily avocado improved cognitive flexibility. Arugula contains more dietary nitrates than beet root per gram. Capers have the highest quercetin content of any food (234mg/100g).',
    benefits: [
      'Avocado lutein selectively accumulates in brain frontal cortex',
      'Arugula: more nitrates than beet root per gram → cerebral blood flow',
      'Capers: highest quercetin content of any food (234mg/100g)',
      'Apple cider vinegar improves insulin sensitivity',
    ],
    shopping: 'Avocados: Costco 6-pack ($6) | Capers: Goya Publix ($3) | Sun-dried tomatoes: Trader Joe\'s ($4) | Apple cider vinegar: Bragg\'s with the Mother ($4)',
  },
  {
    id: 'l3', emoji: '🍱', type: 'Lunch',
    name: 'Miso Soup with Tofu, Wakame & Shiitake',
    time: '20 min', servings: 2, cost: '$2.40',
    calories: 180, protein: '14g', fiber: '4g', difficulty: 'Easy',
    color: '#EEEDFE',
    tags: ['probiotics', 'iodine', 'vitamin D'],
    ingredients: [
      '4 cups kombu dashi or vegetable broth',
      '3 tbsp white (shiro) miso paste',
      '200g silken tofu (cubed)',
      '2 tbsp dried wakame seaweed',
      '1 cup fresh shiitake mushrooms (sliced)',
      '3 green onions (sliced)',
      '1 tbsp low-sodium soy sauce',
      '1 tsp toasted sesame oil',
      '1 tsp fresh ginger (grated)',
    ],
    steps: [
      'Rehydrate dried wakame in cold water for 5 minutes. Drain and set aside.',
      'Bring broth to a gentle simmer. Add sliced shiitake and grated ginger. Cook 5 minutes.',
      'Remove ½ cup of hot broth into a bowl. Whisk in miso paste until completely dissolved.',
      'Return miso mixture to the pot — NEVER bring to a full boil (destroys probiotics).',
      'Add silken tofu cubes and wakame. Serve topped with green onions and sesame oil.',
    ],
    science: 'Miso is a traditionally fermented food containing Aspergillus oryzae, Lactobacillus, and other microorganisms that support gut-brain axis health. Wakame seaweed provides iodine (essential for thyroid hormones regulating brain metabolism). Shiitake contain lentinan (an immunomodulating beta-glucan) and vitamin D2.',
    benefits: [
      'Miso live cultures support gut-brain serotonin pathway',
      'Wakame iodine: essential for thyroid-mediated brain metabolism',
      'Shiitake lentinan: immunomodulating beta-glucan',
      'Never boil miso — heat above 115°F destroys live cultures',
    ],
    shopping: 'White miso: Hikari or Marukome Asian market ($5–7/tub) | Dried wakame: Asian markets ($4) | Silken tofu: Nasoya ($3) | Shiitake: Fresh Asian market ($4)',
  },
  {
    id: 'l4', emoji: '🫓', type: 'Lunch',
    name: 'Falafel Wrap with Tahini & Tabbouleh',
    time: '35 min', servings: 2, cost: '$4.00',
    calories: 520, protein: '20g', fiber: '13g', difficulty: 'Medium',
    color: '#FAECE7',
    tags: ['sesamin', 'low glycemic', 'calcium'],
    ingredients: [
      '1 can chickpeas (drained, very dry)',
      '¼ cup fresh flat-leaf parsley',
      '¼ cup fresh cilantro',
      '1 small yellow onion',
      '3 garlic cloves',
      '1 tsp cumin, 1 tsp coriander',
      '2 tbsp chickpea flour',
      '2 large whole wheat wraps',
      '3 tbsp tahini + water + lemon (for sauce)',
      '1 cup tabbouleh',
      'Sliced cucumber and tomato',
    ],
    steps: [
      'Pulse chickpeas, herbs, onion, garlic, spices in food processor until coarse (NOT smooth).',
      'Add flour and salt. Form into 8–10 disc-shaped patties. Refrigerate 30 minutes.',
      'Make tahini sauce: whisk tahini with lemon juice, garlic, and enough water for a drizzleable consistency.',
      'Cook falafel in olive oil over medium heat, 3 minutes per side, until deeply golden.',
      'Warm wraps. Layer falafel, tabbouleh, cucumber, tomato, and tahini sauce. Roll tightly.',
    ],
    science: 'Sesame tahini contains sesamin and sesamolin — lignans that inhibit delta-5-desaturase, favorably reducing the omega-6:omega-3 ratio in cell membranes. Homemade falafel has a glycemic index of approximately 32 (very low), providing stable blood glucose. Chickpea saponins bind bile acids in the gut, reducing cholesterol reabsorption by 10–15%.',
    benefits: [
      'Tahini sesamin optimizes omega-6:omega-3 ratio in cell membranes',
      'Homemade falafel GI ≈ 32 — no postprandial blood sugar crashes',
      'Chickpea saponins reduce cholesterol reabsorption 10–15%',
      'Tahini: 130mg calcium per 2 tbsp + copper and manganese',
    ],
    shopping: 'Chickpeas: Goya ($1/can) | Tahini: Soom Foods Whole Foods ($8) or Trader Joe\'s Organic ($5) | Whole wheat wraps: Mission ($4) | Fresh herbs: Publix produce ($2 each)',
  },
  {
    id: 'l5', emoji: '🥣', type: 'Lunch',
    name: 'Tempeh Buddha Bowl with Ginger Miso Dressing',
    time: '30 min', servings: 2, cost: '$4.80',
    calories: 550, protein: '32g', fiber: '12g', difficulty: 'Medium',
    color: '#EAF3DE',
    tags: ['fermented protein', 'isoflavones', 'GABA'],
    ingredients: [
      '240g organic tempeh (cubed)',
      '2 cups cooked brown rice',
      '1 cup shelled edamame (thawed)',
      '1 cup shredded purple cabbage',
      '1 large carrot (julienned)',
      '1 ripe avocado (sliced)',
      'Marinade: 2 tbsp soy sauce, 1 tbsp sesame oil, 1 tbsp maple syrup',
      'Dressing: 2 tbsp white miso, 1 tbsp tahini, 1 tsp fresh ginger, 1 lemon, 2 tbsp warm water',
    ],
    steps: [
      'Cube tempeh. Combine soy sauce, sesame oil, and maple syrup. Marinate tempeh 15 minutes.',
      'Bake marinated tempeh at 400°F for 20 minutes (flip halfway) until caramelized.',
      'Whisk all dressing ingredients together, adding warm water to thin to drizzleable consistency.',
      'Arrange brown rice, edamame, purple cabbage, carrot, and avocado in two bowls.',
      'Top with tempeh and generous drizzle of ginger miso dressing.',
    ],
    science: 'Tempeh fermentation reduces phytic acid content by 40%, dramatically improving bioavailability of zinc, iron, and manganese. Purple cabbage contains 90mg anthocyanins per cup — comparable to blueberries. Soy isoflavones exhibit cardioprotective effects (JAMA Internal Medicine meta-analysis, 2003). Brown rice contains naturally occurring GABA.',
    benefits: [
      'Fermentation reduces phytic acid 40% — doubles mineral absorption',
      'Purple cabbage: 90mg anthocyanins per cup (equals blueberries)',
      'Soy isoflavones: cardioprotective via clinical meta-analysis evidence',
      'Brown rice GABA supports calm, focused mental state',
    ],
    shopping: 'Tempeh: Lightlife Organic Whole Foods or Publix ($3–4) | Edamame: Costco frozen shelled ($8/4lb) | Brown rice: Lundberg Organic ($6) | Miso paste: same tub as miso soup',
  },
  {
    id: 'l6', emoji: '🫐', type: 'Lunch',
    name: 'Roasted Beet & Arugula Salad with Goat Cheese',
    time: '55 min', servings: 2, cost: '$4.40',
    calories: 420, protein: '12g', fiber: '8g', difficulty: 'Medium',
    color: '#FBEAF0',
    tags: ['dietary nitrates', 'blood pressure', 'Nrf2 activation'],
    ingredients: [
      '4 medium beets (roasted)',
      '4 cups baby arugula',
      '¼ cup walnuts (toasted)',
      '60g fresh goat cheese (crumbled)',
      '¼ cup pomegranate arils',
      'Dressing: 3 tbsp balsamic, 3 tbsp EVOO, 1 tsp honey, 1 tsp Dijon',
      'Salt, pepper, fresh thyme',
    ],
    steps: [
      'Preheat oven to 400°F. Wrap individual beets in foil with a drizzle of olive oil. Roast 45 minutes.',
      'Let cool, then peel (skins slide off easily). Slice into quarters or wedges.',
      'Toast walnuts in a dry pan over medium heat, 3–4 minutes until fragrant.',
      'Whisk dressing ingredients together.',
      'Arrange arugula. Top with beets, crumble goat cheese, scatter walnuts and pomegranate arils. Drizzle dressing.',
    ],
    science: 'Beets are the richest dietary source of inorganic nitrates, which reduce to nitric oxide — a powerful vasodilator. A landmark 2010 Hypertension study showed dietary nitrates reduced systolic blood pressure by 4–10 mmHg. Pomegranate punicalagin reduced carotid plaque by 30% over 3 years (Aviram et al., Clinical Nutrition, 2004 RCT).',
    benefits: [
      'Beet nitrates reduce systolic BP by 4–10 mmHg (clinical RCT)',
      'Pomegranate reduced arterial plaque 30% over 3 years (RCT)',
      'Arugula isothiocyanates activate Nrf2 master antioxidant gene',
      'Walnuts: 2.5g ALA omega-3 + polyphenols that reduce ox-LDL',
    ],
    shopping: 'Beets: Love Beets pre-cooked pouches (~$5, saves 45 min) or Costco multipack ($6) | Goat cheese: Laura Chenel or Trader Joe\'s ($4–5) | Pomegranate arils: Costco POM ($7)',
  },
];

// ─── DINNERS ──────────────────────────────────────────────────
export const DINNERS = [
  {
    id: 'd0', emoji: '🍛', type: 'Dinner',
    name: 'Saag Dal — Lentils with Spinach & Spices',
    time: '40 min', servings: 4, cost: '$2.20',
    calories: 380, protein: '22g', fiber: '18g', difficulty: 'Medium',
    color: '#EAF4EE',
    tags: ['folate', 'butyrate', '22% lower heart risk'],
    ingredients: [
      '1½ cups yellow split peas or red lentils',
      '4 cups low-sodium vegetable broth',
      '4 cups fresh baby spinach',
      '1 can (14oz) diced tomatoes',
      '1 large onion (finely diced)',
      '4 garlic cloves (minced)',
      '1 tbsp fresh ginger (grated)',
      '2 tsp cumin seeds',
      '1 tsp coriander, 1 tsp turmeric, ½ tsp garam masala',
      '2 tbsp ghee or coconut oil',
      'Salt to taste',
    ],
    steps: [
      'Cook lentils in broth with turmeric until completely soft, about 20 minutes.',
      'Tarka: heat ghee over medium-high. Add cumin seeds and let them pop (30 seconds).',
      'Add diced onion. Cook 10–12 minutes until deeply golden-brown.',
      'Add garlic, ginger, coriander, tomatoes. Cook 5 minutes until thickened.',
      'Pour tomato mixture into lentils. Add spinach. Simmer 5 minutes. Season with garam masala.',
    ],
    science: 'A 2016 Circulation study found ≥4 legume servings per week associated with 22% lower coronary heart disease risk. Folate and B6 from lentils synergistically reduce homocysteine — every 5 µmol/L decrease = 19% lower stroke risk. Ghee contains butyrate, a short-chain fatty acid that directly nourishes colonocytes.',
    benefits: [
      '22% lower heart disease risk with ≥4 legume servings/week',
      'Folate + B6 reduce homocysteine → 19% lower stroke risk',
      'Ghee butyrate nourishes gut lining and reduces inflammation',
      '18g fiber — highest-fiber dish in this entire plan',
    ],
    shopping: 'Lentils: Goya ($2/lb) or Indian grocery bulk ($1.20/lb) | Ghee: 4th & Heart Whole Foods ($8) | Spices: Indian grocery 70% cheaper than McCormick | Budget: $8.80/pot = $2.20/serving',
  },
  {
    id: 'd1', emoji: '🍄', type: 'Dinner',
    name: 'Wild Mushroom Risotto with Parmesan & Thyme',
    time: '50 min', servings: 4, cost: '$5.20',
    calories: 480, protein: '18g', fiber: '3g', difficulty: 'Hard',
    color: '#FFF8E7',
    tags: ['ergothioneine', 'vitamin D', 'cognitive protection'],
    ingredients: [
      '1½ cups Arborio rice',
      '1 oz dried porcini mushrooms',
      '2 cups mixed fresh mushrooms (cremini, shiitake, oyster)',
      '4 cups warm vegetable broth',
      '1 cup dry white wine',
      '1 large onion (finely diced)',
      '4 garlic cloves (minced)',
      '60g Parmigiano-Reggiano (grated)',
      '3 tbsp unsalted butter',
      '2 tbsp extra virgin olive oil',
      'Fresh thyme and flat-leaf parsley',
    ],
    steps: [
      'Rehydrate porcini in 1 cup hot water for 20 minutes. Strain and save liquid. Chop mushrooms.',
      'Sauté fresh mushrooms in butter over high heat until deeply golden (~6 min). Set aside.',
      'Sauté onion in oil 5 minutes. Add garlic and rice; stir to coat 2 minutes.',
      'Add wine; stir until fully absorbed. Add warm broth one ladle at a time, stirring constantly, 20–22 minutes.',
      'Remove from heat. Stir in butter and Parmesan (mantecatura). Fold in mushrooms. Rest 2 minutes.',
    ],
    science: 'Mushrooms are the only food containing ergothioneine — a unique antioxidant that accumulates specifically in brain mitochondria, protecting against oxidative DNA damage. People eating mushrooms twice weekly have significantly lower rates of mild cognitive impairment (Feng et al., Journal of Alzheimer\'s Disease, 2019, n=663).',
    benefits: [
      'Ergothioneine uniquely accumulates in brain mitochondria',
      'Regular mushroom consumption → significantly lower MCI rate (n=663)',
      'Dried porcini: up to 25µg vitamin D2 per 100g',
      'Mantecatura technique creates optimal creamy texture and satiety',
    ],
    shopping: 'Arborio: RiceSelect Publix or Target ($5) | Dried porcini: Trader Joe\'s ($5) | Fresh mushrooms: Costco 2lb mix ($7) | Parmesan: Costco Parmigiano-Reggiano DOP block ($12/lb — buy only authentic DOP)',
  },
  {
    id: 'd2', emoji: '🧡', type: 'Dinner',
    name: 'Chickpea Tikka Masala',
    time: '35 min', servings: 4, cost: '$2.80',
    calories: 420, protein: '18g', fiber: '14g', difficulty: 'Easy',
    color: '#FAECE7',
    tags: ['lycopene', 'antioxidants', 'heart'],
    ingredients: [
      '2 cans (15oz) chickpeas (drained, rinsed)',
      '1 can (13.5oz) full-fat coconut milk',
      '1 can (14oz) crushed San Marzano tomatoes',
      '1 large yellow onion (finely diced)',
      '5 garlic cloves (minced)',
      '2 tbsp fresh ginger (grated)',
      '3 tbsp tikka masala paste (Patak\'s)',
      '1 tsp garam masala, 1 tsp cumin',
      '2 tbsp extra virgin olive oil',
      'Fresh cilantro, brown basmati rice',
    ],
    steps: [
      'Cook diced onion in olive oil over medium heat for 15 minutes until deeply caramelized. Do not rush.',
      'Add garlic, ginger, tikka masala paste, and cumin. Cook 3 minutes until very fragrant.',
      'Add crushed tomatoes. Cook 8 minutes, stirring frequently, until sauce darkens.',
      'Pour in coconut milk. Add chickpeas. Simmer 10 minutes.',
      'Add garam masala. Adjust salt. Top with fresh cilantro. Serve over brown basmati rice.',
    ],
    science: 'Tomatoes cooked in oil release 3–4× more bioavailable lycopene than raw tomatoes. Each 2mg/day increase in dietary lycopene is associated with 9% lower cardiovascular risk (Cancer Causes & Control, 2020). Coconut milk lauric acid raises HDL cholesterol more than any other dietary fat studied.',
    benefits: [
      'Cooked tomato in oil = 3–4× more bioavailable lycopene',
      'Every 2mg/day lycopene → 9% lower cardiovascular risk',
      'Coconut lauric acid raises HDL more than any other dietary fat',
      'Caramelized onion quercetin has superior bioavailability vs raw',
    ],
    shopping: 'Tikka paste: Patak\'s Publix ($4/jar — one jar makes 2 batches) | Coconut milk: Thai Kitchen ($2.50) | Tomatoes: San Marzano DOP ($3/can) | Brown basmati: Lundberg Organic ($6)',
  },
  {
    id: 'd3', emoji: '🌿', type: 'Dinner',
    name: 'Stuffed Portobello with Quinoa & Kale',
    time: '40 min', servings: 2, cost: '$5.60',
    calories: 460, protein: '22g', fiber: '9g', difficulty: 'Medium',
    color: '#EAF3DE',
    tags: ['sulforaphane', 'vitamin D', 'Nrf2 activation'],
    ingredients: [
      '4 large portobello mushroom caps',
      '1 cup cooked quinoa',
      '2 cups lacinato kale (finely chopped)',
      '½ cup oil-packed sun-dried tomatoes (chopped)',
      '¼ cup pine nuts',
      '60g fresh goat cheese (crumbled)',
      '3 garlic cloves (minced)',
      '2 tbsp extra virgin olive oil',
      '1 tbsp balsamic vinegar',
      'Fresh basil, lemon zest',
    ],
    steps: [
      'Brush portobello caps with olive oil. Roast gill-side up at 400°F for 10 minutes. Drain liquid.',
      'Sauté chopped kale with garlic and balsamic vinegar in olive oil for 4–5 minutes until wilted.',
      'Combine cooked quinoa with sautéed kale, sun-dried tomatoes, pine nuts, and lemon zest.',
      'Fill mushroom caps generously. Top each with crumbled goat cheese.',
      'Roast 15 more minutes until cheese is lightly golden. Garnish with fresh basil.',
    ],
    science: 'Portobello mushrooms placed gill-side up in direct midday sunlight for 2 hours can synthesize up to 400% DV of vitamin D2. Kale glucoraphanin hydrolyzes to sulforaphane upon chopping — the most potent known dietary activator of the Nrf2 transcription factor, upregulating 200+ cytoprotective genes.',
    benefits: [
      'Sun-exposed portobello: up to 400% DV vitamin D2',
      'Kale sulforaphane activates Nrf2 → 200+ cytoprotective genes',
      'Sulforaphane equivalent to 2 cups kale improves blood glucose 10%',
      'Pine nuts stimulate CCK — the gut satiety hormone',
    ],
    shopping: 'Portobello caps: All grocery stores ($3–4 for 4) | Pine nuts: Trader Joe\'s ($6, best value) | Kale: Costco pre-washed lacinato ($5) | Goat cheese: Laura Chenel or Trader Joe\'s ($4–5)',
  },
  {
    id: 'd4', emoji: '🌶️', type: 'Dinner',
    name: 'Sweet Potato & Black Bean Chili',
    time: '45 min', servings: 6, cost: '$1.60',
    calories: 340, protein: '16g', fiber: '18g', difficulty: 'Easy',
    color: '#FAECE7',
    tags: ['beta-carotene', 'DASH diet', 'anthocyanins'],
    ingredients: [
      '2 large sweet potatoes (peeled, ½" cubed)',
      '2 cans black beans (drained, rinsed)',
      '1 can diced tomatoes',
      '1 can corn (or 1½ cups frozen)',
      '1 large yellow onion (diced)',
      '4 garlic cloves (minced)',
      '2 tbsp extra virgin olive oil',
      '2 tbsp chili powder, 2 tsp cumin, 1 tsp smoked paprika',
      '3 cups low-sodium vegetable broth',
      'Juice of 1 lime',
      'Toppings: sliced avocado, cilantro, Greek yogurt',
    ],
    steps: [
      'Heat olive oil in a large Dutch oven. Add diced onion, cook 5 minutes.',
      'Add garlic and all dry spices. Cook 2 minutes until fragrant.',
      'Add cubed sweet potatoes and stir to coat with spices.',
      'Pour in tomatoes, broth, black beans, and corn. Bring to a boil.',
      'Reduce heat. Simmer 25–30 minutes until sweet potatoes are tender. Stir in lime juice.',
    ],
    science: 'A 2009 Archives of Internal Medicine RCT found a DASH dietary pattern rich in legumes and sweet potatoes reduced systolic blood pressure by 11.4 mmHg — equivalent in magnitude to many first-line antihypertensive medications. Black beans contain anthocyanins with similar neuroprotective activity to blueberries.',
    benefits: [
      'DASH-style diet lowers systolic BP 11.4 mmHg (equivalent to medication)',
      'Black bean anthocyanins: same neuroprotective class as blueberries',
      'Sweet potato beta-carotene: 9mg per potato (vitamin A precursor)',
      '$1.60/serving — best nutrition-per-dollar meal in the entire plan',
    ],
    shopping: 'Sweet potatoes: Costco 5lb bag ($5) | Black beans: Goya Walmart ($0.85/can) | Chili powder: Gebhardt brand ($3) | Budget tip: this 6-serving pot costs under $10',
  },
  {
    id: 'd5', emoji: '🍆', type: 'Dinner',
    name: 'Baked Eggplant Parmesan',
    time: '60 min', servings: 4, cost: '$4.00',
    calories: 380, protein: '22g', fiber: '8g', difficulty: 'Medium',
    color: '#EEEDFE',
    tags: ['nasunin', 'ACE inhibitor', 'lycopene'],
    ingredients: [
      '2 large eggplants (sliced ½" thick)',
      '2 cups high-quality marinara sauce (Rao\'s)',
      '1½ cups part-skim mozzarella (shredded)',
      '60g Parmigiano-Reggiano (grated)',
      '2 large eggs',
      '1 cup whole wheat panko breadcrumbs',
      '1 tsp garlic powder, 1 tsp dried Italian herbs',
      '2 tbsp extra virgin olive oil',
      'Fresh basil, coarse sea salt',
    ],
    steps: [
      'Slice eggplant. Salt generously on both sides. Rest on rack 30 minutes. Rinse and pat completely dry.',
      'Dip each slice in beaten egg, then breadcrumbs mixed with garlic powder and herbs.',
      'Arrange on oiled baking sheets. Brush tops with olive oil. Bake at 400°F 20 min, flip, 15 more min.',
      'Layer in baking dish: marinara → eggplant → mozzarella → Parmesan. Repeat.',
      'Cover and bake 20 min. Uncover and bake 10 more min until bubbly. Rest 10 min.',
    ],
    science: 'Eggplant nasunin (750mg/100g) specifically protects phospholipids in brain cell membranes from free radical damage and chelates excess iron. Eggplant caffeic acid and chlorogenic acid inhibit angiotensin-converting enzyme (ACE) through the same molecular mechanism as ACE inhibitor antihypertensive medications.',
    benefits: [
      'Nasunin 750mg/100g: protects brain cell membrane phospholipids',
      'Eggplant phenolics inhibit ACE (same mechanism as BP medications)',
      'Baking vs frying: 70% less fat, all antioxidants preserved',
      'Rao\'s marinara: concentrated lycopene, no added sugar or seed oils',
    ],
    shopping: 'Eggplant: All stores ($1.50–2 each) | Marinara: Rao\'s Homemade Costco 2-pack ($9 — major savings) | Mozzarella: Galbani Whole Milk ($5) | Parmesan: same Costco DOP block',
  },
  {
    id: 'd6', emoji: '🥥', type: 'Dinner',
    name: 'Thai Green Curry with Vegetables & Tofu',
    time: '35 min', servings: 4, cost: '$3.60',
    calories: 420, protein: '20g', fiber: '7g', difficulty: 'Medium',
    color: '#EAF4EE',
    tags: ['MCT', 'sulforaphane', 'anti-inflammatory'],
    ingredients: [
      '400g extra-firm tofu (pressed, cubed)',
      '1 can (13.5oz) full-fat coconut milk',
      '2 tbsp green curry paste (Maesri brand)',
      '1 medium zucchini (sliced)',
      '1 red bell pepper (sliced)',
      '1 cup snap peas',
      '1½ cups broccoli florets',
      '1 can (8oz) bamboo shoots (drained)',
      '2 tbsp coconut aminos or soy sauce',
      '1 tbsp fresh lime juice',
      'Fresh Thai basil, brown jasmine rice',
    ],
    steps: [
      'Press tofu 15 minutes. Pan-fry in coconut oil over high heat until golden on all sides (~8 min).',
      'In same pan, fry curry paste over medium heat 2 minutes, stirring constantly until fragrant.',
      'Pour in coconut milk. Stir vigorously to combine. Bring to gentle simmer.',
      'Add vegetables in order: broccoli first (3 min), zucchini and pepper (3 min), snap peas (2 min).',
      'Add tofu, coconut aminos, and lime juice. Simmer 3 more minutes. Top with Thai basil.',
    ],
    science: 'Thai green curry paste contains lemongrass citral that induces apoptosis in cancer cells and inhibits pro-inflammatory cytokines. Galangal inhibits 5-lipoxygenase (5-LOX), reducing leukotriene synthesis — a key cardiovascular benefit. Coconut MCTs are converted to ketones within 30 minutes, providing rapid alternative brain fuel.',
    benefits: [
      'Lemongrass citral: inhibits pro-inflammatory cytokines',
      'Galangal inhibits 5-LOX → reduces cardiovascular leukotrienes',
      'Coconut MCTs → brain ketones within 30 minutes',
      'Broccoli sulforaphane activates Nrf2 → 200+ cytoprotective genes',
    ],
    shopping: 'Green curry paste: Maesri Asian market ($1–2/can — far superior to grocery brands) | Coconut milk: Thai Kitchen ($2.50) | Thai basil: Asian grocery ($2) | Brown jasmine rice: Lotus Foods ($6)',
  },
];

// ─── ALL MEALS COMBINED ────────────────────────────────────────
export const ALL_MEALS = [...BREAKFASTS, ...LUNCHES, ...DINNERS];

export function getMealById(id) {
  return ALL_MEALS.find(m => m.id === id);
}

// ─── 4-WEEK PLAN ──────────────────────────────────────────────
export const WEEK_PLAN = [
  [
    { b: 0, l: 0, d: 0 }, { b: 1, l: 1, d: 1 }, { b: 2, l: 2, d: 2 },
    { b: 3, l: 3, d: 3 }, { b: 4, l: 4, d: 4 }, { b: 5, l: 5, d: 5 }, { b: 6, l: 6, d: 6 },
  ],
  [
    { b: 1, l: 0, d: 2 }, { b: 2, l: 1, d: 3 }, { b: 3, l: 2, d: 4 },
    { b: 4, l: 3, d: 5 }, { b: 5, l: 4, d: 6 }, { b: 6, l: 5, d: 0 }, { b: 0, l: 6, d: 1 },
  ],
  [
    { b: 2, l: 1, d: 4 }, { b: 3, l: 2, d: 5 }, { b: 4, l: 3, d: 6 },
    { b: 5, l: 4, d: 0 }, { b: 6, l: 5, d: 1 }, { b: 0, l: 6, d: 2 }, { b: 1, l: 0, d: 3 },
  ],
  [
    { b: 3, l: 2, d: 6 }, { b: 4, l: 3, d: 0 }, { b: 5, l: 4, d: 1 },
    { b: 6, l: 5, d: 2 }, { b: 0, l: 6, d: 3 }, { b: 1, l: 0, d: 4 }, { b: 2, l: 1, d: 5 },
  ],
];

export const DAY_NAMES = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
export const DAY_SHORT = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

// ─── SCIENCE DATA ─────────────────────────────────────────────
export const SCIENCE_FACTS = [
  {
    icon: '🧠', title: 'MIND Diet Effect', stat: '53%',
    description: 'reduction in Alzheimer\'s disease risk with strict adherence to the MIND diet pattern',
    source: 'Morris et al., Alzheimer\'s & Dementia, 2015, n=923',
  },
  {
    icon: '❤️', title: 'PREDIMED Trial', stat: '30%',
    description: 'reduction in major cardiovascular events over 5 years on a Mediterranean plant-based diet',
    source: 'Estruch et al., New England Journal of Medicine, 2013, n=7,447',
  },
  {
    icon: '🫐', title: 'Blueberry Cognition', stat: '25%',
    description: 'improvement in memory and cognitive function from regular anthocyanin-rich berry consumption',
    source: 'Devore et al., JAMA Internal Medicine, 2012, n=16,010',
  },
  {
    icon: '🌱', title: 'Legume Heart Protection', stat: '22%',
    description: 'lower coronary heart disease risk with 4 or more legume servings per week',
    source: 'Afshin et al., Circulation, 2016, n=432,000',
  },
  {
    icon: '🥗', title: 'Dietary Nitrates', stat: '10 mmHg',
    description: 'acute systolic blood pressure reduction from dietary nitrates equivalent to 2 medium beets',
    source: 'Webb et al., Hypertension Journal, 2010 (landmark RCT)',
  },
  {
    icon: '🍄', title: 'Mushroom Protection', stat: '2×',
    description: 'lower likelihood of mild cognitive impairment in adults eating mushrooms more than twice weekly',
    source: 'Feng et al., Journal of Alzheimer\'s Disease, 2019, n=663',
  },
];

export const PILLARS = [
  {
    number: 1, color: '#2D6A4F',
    title: 'Anti-Inflammatory Architecture',
    description: 'Every recipe contains a clinically validated anti-inflammatory compound — curcumin, omega-3, quercetin, resveratrol, or sulforaphane — each targeting different inflammatory pathways for synergistic effect.',
  },
  {
    number: 2, color: '#40916C',
    title: 'Fiber Maximization & Microbiome Support',
    description: 'Target 35–45g fiber daily (US average: 15g). Diverse fiber types — soluble, insoluble, resistant starch — feed 500+ bacterial species, promoting microbiome diversity that predicts metabolic health.',
  },
  {
    number: 3, color: '#1B2A4A',
    title: 'Polyphenol Density',
    description: 'Target 1,500+ mg polyphenols daily — 3× the population average. Polyphenols act through direct antioxidant activity, epigenetic modification (sirtuin longevity gene activation), and prebiotic effects on gut flora.',
  },
  {
    number: 4, color: '#A63A1A',
    title: 'Heart-Healthy Fat Architecture',
    description: 'Fat quality, not quantity, determines cardiovascular risk. This plan emphasizes olive oil (oleic acid + oleocanthal), avocado (monounsaturated + lutein), and ALA omega-3 from walnuts and flaxseed.',
  },
  {
    number: 5, color: '#C4920F',
    title: 'Glycemic Intelligence',
    description: 'Every carbohydrate is paired with fiber, protein, or fat to blunt blood glucose response. Chronically elevated blood sugar glycates brain proteins (forming AGEs), accelerating neurodegeneration.',
  },
  {
    number: 6, color: '#40916C',
    title: 'Complete Amino Acid Profiles',
    description: 'Each day provides all 9 essential amino acids through strategic combining: legumes + grains, complete proteins (tofu, quinoa, hemp seeds). Amino acids are direct precursors to neurotransmitters.',
  },
  {
    number: 7, color: '#1B2A4A',
    title: 'Micronutrient Saturation',
    description: 'Key nutrients for brain and heart — B12, folate, magnesium, zinc, iodine, selenium — are specifically targeted. Vegetarian deficiency risks are addressed through targeted food choices and supplementation.',
  },
];

export const SUPPLEMENTS = [
  {
    name: 'Vitamin B12',
    dose: '500mcg methylcobalamin daily OR 2,500mcg weekly',
    why: 'Myelin sheath integrity, red blood cell formation, and neurological function. B12 deficiency causes irreversible nerve damage and is present in 40–90% of vegetarians without supplementation.',
    cost: '~$8–12/mo',
    brands: 'Jarrow Methylcobalamin, Country Life B12, Solgar Methylcobalamin — always choose methylcobalamin form, not cyanocobalamin.',
  },
  {
    name: 'Vitamin D3 + K2',
    dose: '2,000–4,000 IU vitamin D3 + 100mcg K2 (MK-7) daily',
    why: 'Bone health, immune function, mood regulation, cardiovascular health. 80% of Americans are D-deficient. K2 ensures calcium goes to bones, not arteries. Test 25-OH vitamin D annually — target 40–60 ng/mL.',
    cost: '~$8–15/mo',
    brands: 'Thorne D3+K2, Nature Made D3, NOW Foods Vitamin D3 Softgels — liquid drops absorb better than pills.',
  },
  {
    name: 'Algae-Based DHA + EPA',
    dose: '250–500mg combined DHA+EPA daily',
    why: 'DHA constitutes 40% of brain cell membrane polyunsaturated fats. Algae is the original source (fish get it from algae) — zero mercury, zero ocean contamination, fully sustainable.',
    cost: '~$20–30/mo',
    brands: 'Nordic Naturals Algae Omega, Ovega-3 Plant-Based Omega-3, Testa Omega-3 — choose products specifying both DHA and EPA.',
  },
  {
    name: 'Iodine',
    dose: '150mcg iodine daily (unless eating sea vegetables 3× per week)',
    why: 'Iodine is essential for thyroid hormones T3 and T4, which regulate basal metabolic rate and brain metabolism. Deficiency is the world\'s #1 preventable cause of cognitive impairment.',
    cost: '~$5–8/mo',
    brands: 'Thorne Iodine + Selenomethionine, Life Extension Sea-Iodine — or eat dulse/nori/wakame 3× weekly as a whole-food alternative.',
  },
];

// ─── SHOPPING DATA ─────────────────────────────────────────────
export const STORES = [
  {
    icon: '🏢', name: 'Costco / Sam\'s Club', type: 'Bulk buying champion', savings: '40–60% off staples',
    items: 'Frozen wild blueberries, walnuts, avocados, Kirkland EVOO, Greek yogurt, Rao\'s marinara (2-pack), canned tomatoes, almond milk cases, nut butters, Parmigiano-Reggiano',
  },
  {
    icon: '🛒', name: 'Trader Joe\'s', type: 'Best value specialty foods', savings: '20–40% off specialty',
    items: 'Goat cheese, Kalamata olives, tahini, tempeh, pine nuts, granola, frozen edamame, coconut milk, dried lentils, aged balsamic vinegar, sun-dried tomatoes in oil',
  },
  {
    icon: '🌿', name: 'Whole Foods Market', type: 'Organic & premium ingredients', savings: '30% with Amazon Prime',
    items: 'Highest-quality organic produce, specialty grains, hemp seeds, nutritional yeast, supplements (best selection), bulk bins for spices and dried goods',
  },
  {
    icon: '🌏', name: 'Asian / Indian Grocery', type: 'Spices, fermented & specialty', savings: '70–80% off spices',
    items: 'Turmeric, cumin, coriander (10× cheaper), white miso paste, silken tofu, tempeh, dried wakame/nori, coconut milk, green curry paste (Maesri brand), Thai basil, galangal',
  },
  {
    icon: '🏪', name: 'Publix / Kroger / Safeway', type: 'Weekly fresh produce', savings: 'BOGO + loyalty savings',
    items: 'Local seasonal produce, fresh herbs, dairy, eggs, most pantry staples — use the store app for BOGO deals and digital coupons',
  },
];

export const COST_DATA = [
  { label: 'Breakfasts (7 varieties, avg)', daily: '$2.80', weekly: '$19.60', monthly: '$84', isTotal: false },
  { label: 'Lunches (7 varieties, avg)', daily: '$3.20', weekly: '$22.40', monthly: '$96', isTotal: false },
  { label: 'Dinners (7 varieties, avg)', daily: '$3.40', weekly: '$23.80', monthly: '$102', isTotal: false },
  { label: 'Pantry staples (oils, spices)', daily: '—', weekly: '$12.00', monthly: '$48', isTotal: false },
  { label: 'Evidence-based supplements', daily: '—', weekly: '$7.00', monthly: '$28', isTotal: false },
  { label: 'GRAND TOTAL', daily: '$11.50', weekly: '$84.80', monthly: '$358', isTotal: true },
];

export const SHOPPING_TIPS = [
  {
    title: 'Buy bulk at Costco for staples',
    detail: 'Frozen wild blueberries, walnuts, quinoa, olive oil, Greek yogurt, almond milk — save 40–60% vs grocery store. Membership pays for itself in 2 months.',
  },
  {
    title: 'Shop seasonal produce always',
    detail: 'Seasonal produce costs 30–50% less, is picked at peak ripeness (higher nutrition), and supports local farms. Farmer\'s markets are often the cheapest source.',
  },
  {
    title: 'Use the Dirty Dozen / Clean Fifteen guide',
    detail: 'Buy organic: strawberries, spinach, kale, bell peppers. Buy conventional: avocados, onions, sweet potatoes, mushrooms. Saves ~$30/month.',
  },
  {
    title: 'Freeze everything strategically',
    detail: 'Cooked lentils and beans freeze 3 months in portions. Fresh berries, herbs, and spinach freeze perfectly. Ginger and turmeric root grate frozen. Eliminates food waste.',
  },
  {
    title: 'Spices: shop Indian grocery stores exclusively',
    detail: 'Turmeric, cumin, coriander, cardamom cost 70–80% less at Indian grocery stores vs. McCormick. Same or higher quality. Buy in larger bags.',
  },
  {
    title: 'Batch cook Sunday — save 45 min/day',
    detail: 'Cook a large pot of lentils or chickpeas, a batch of quinoa or brown rice, and roast a sheet pan of vegetables every Sunday. Mix and match throughout the week.',
  },
  {
    title: 'Grow herbs in a sunny window',
    detail: 'Basil, parsley, cilantro, rosemary, and mint grow easily from $1–2 plants. Each plant provides months of fresh herbs — the most expensive per-ounce grocery item.',
  },
  {
    title: 'Compare unit prices, never shelf prices',
    detail: 'Bulk bins at Whole Foods often beat pre-packaged goods. Costco 5lb quinoa is 60% cheaper per ounce than grocery store boxes. Always calculate $/oz or $/lb.',
  },
];
